services:
  - type: web
    name: intern-portal-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: intern-portal-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

